VERSION = '0.1.0'

ENDPOINT_AI = 'ai'
ENDPOINT_HH = 'hh'
QUERY_PARAM_COMMAND = 'command'
QUERY_PARAM_VALUE = 'value'
COMMAND_GET_STATUS = 'getDeviceStatus'
COMMAND_GET_MODEL_DESC = 'getModelDescription'
COMMAND_GET_PROGRAM = 'getProgram'
COMMAND_GET_COMMAND = 'getCommand'

DEVICE_TYPE_UNKNOWN = 'UNKNOWN'
DEVICE_TYPE_WASHING_MACHINE = 'WASHING_MACHINE'
DEVICE_TYPE_DRYER = 'DRYER'

MODEL_MATCH_WASHING_MACHINE = 'wash'
MODEL_MATCH_DRYER = 'dry'
