VERSION = '0.1.1'

ENDPOINT_AI = 'ai'
ENDPOINT_HH = 'hh'
QUERY_PARAM_COMMAND = 'command'
QUERY_PARAM_VALUE = 'value'
COMMAND_GET_STATUS = 'getDeviceStatus'
COMMAND_GET_MODEL_DESC = 'getModelDescription'
COMMAND_GET_MACHINE_TYPE = 'getMachineType'
COMMAND_GET_PROGRAM = 'getProgram'
COMMAND_GET_COMMAND = 'getCommand'


DEVICE_TYPE_UNKNOWN = 'UNKNOWN'
DEVICE_TYPE_WASHING_MACHINE = 'WASHING_MACHINE'
DEVICE_TYPE_DRYER = 'DRYER'
DEVICE_TYPE_DISHWASHER = 'DISHWASHER'
DEVICE_TYPE_OVEN = 'OVEN'
DEVICE_TYPE_STEAMER = 'STEAMER'
DEVICE_TYPE_MICRO_STEAM = 'MICRO_STEAM'
DEVICE_TYPE_MICROWAVE = 'MICROWAVE'
DEVICE_TYPE_COFFEE_CENTER = 'COFFEE_CENTER'
DEVICE_TYPE_RANGE_HOOD = 'RANGE_HOOD'
DEVICE_TYPE_FRIDGE = 'FRIDGE'
DEVICE_TYPE_WINE_COOLER = 'WINE_COOLER'
DEVICE_TYPE_REFRESH_BUTLER = 'REFRESH_BUTLER'
DEVICE_TYPE_GLASS_CERAMIC = 'GLASS_CERAMIC'
DEVICE_TYPE_CARD_SYSTEM = 'CARD_SYSTEM '
DEVICE_TYPE_COIN_SYSTEM = 'COIN_SYSTEM'

DEVICE_TYPE_SHORT_WASHING_MACHINE = 'WA'
DEVICE_TYPE_SHORT_DRYER = 'WT'
DEVICE_TYPE_SHORT_DISHWASHER = 'GS'
DEVICE_TYPE_SHORT_OVEN = 'BO'
DEVICE_TYPE_SHORT_STEAMER = 'ST'
DEVICE_TYPE_SHORT_MICRO_STEAM = 'MS'
DEVICE_TYPE_SHORT_MICROWAVE = 'UW'
DEVICE_TYPE_SHORT_COFFEE_CENTER = 'CC'
DEVICE_TYPE_SHORT_RANGE_HOOD = 'DA'
DEVICE_TYPE_SHORT_FRIDGE = 'KS'
DEVICE_TYPE_SHORT_WINE_COOLER = 'WC'
DEVICE_TYPE_SHORT_REFRESH_BUTLER = 'RB'
DEVICE_TYPE_SHORT_GLASS_CERAMIC = 'GK'
DEVICE_TYPE_SHORT_CARD_SYSTEM = 'CS '
DEVICE_TYPE_SHORT_COIN_SYSTEM = 'CO'

DEVICE_TYPE_MAPPING = {
    DEVICE_TYPE_SHORT_WASHING_MACHINE: DEVICE_TYPE_WASHING_MACHINE,
    DEVICE_TYPE_SHORT_DRYER: DEVICE_TYPE_DRYER,
    DEVICE_TYPE_SHORT_DISHWASHER: DEVICE_TYPE_DISHWASHER,
    DEVICE_TYPE_SHORT_OVEN: DEVICE_TYPE_OVEN,
    DEVICE_TYPE_SHORT_STEAMER: DEVICE_TYPE_STEAMER,
    DEVICE_TYPE_SHORT_MICRO_STEAM: DEVICE_TYPE_MICRO_STEAM,
    DEVICE_TYPE_SHORT_MICROWAVE: DEVICE_TYPE_MICROWAVE,
    DEVICE_TYPE_SHORT_COFFEE_CENTER: DEVICE_TYPE_COFFEE_CENTER,
    DEVICE_TYPE_SHORT_RANGE_HOOD: DEVICE_TYPE_RANGE_HOOD,
    DEVICE_TYPE_SHORT_FRIDGE: DEVICE_TYPE_FRIDGE,
    DEVICE_TYPE_SHORT_WINE_COOLER: DEVICE_TYPE_WINE_COOLER,
    DEVICE_TYPE_SHORT_REFRESH_BUTLER: DEVICE_TYPE_REFRESH_BUTLER,
    DEVICE_TYPE_SHORT_GLASS_CERAMIC: DEVICE_TYPE_GLASS_CERAMIC,
    DEVICE_TYPE_SHORT_CARD_SYSTEM: DEVICE_TYPE_CARD_SYSTEM,
    DEVICE_TYPE_SHORT_COIN_SYSTEM: DEVICE_TYPE_COIN_SYSTEM
}

